language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script: composer install --dev --prefer-source > /dev/null

script: vendor/bin/phpspec run -n -f pretty --verbose

notifications:
    email: toon.verwerft@phpro.be
